### ISSUE TITLE
Klarstellung bzgl. Eventeintragung im Eventkalender

### ISSUE THREAD

**Issue by Hetti** [c3wien/c3w.at-pages#15]
Da es unterschiedliche Meinungen gibt bzgl. Aufnahme in den Eventkalender unter https://c3w.at/events/
möchte ich um Klarstellung bitten unter welchen Umständen ein Event in diesen Kalender aufgenommen wird.

Laut Informationen von aktuellen Vorstandsmitgliedern sei es gewünscht, dass das Event im Rahmen eines Caffeine's vorgestellt werden soll bevor es aufgenommen wird.

Sollte dies der gewünschte Modus sein, möge das bitte klargestellt werden auf einer Seite, damit interessierte Personen die ein Event bewerben möchten informiert sind.

**Comment by MacLemon** [comment]
Nach Rücksprache:
Es wurde ein Prozess dafür besprochen und es gibt ein Kalenderteam welches sich um Kalendereinträge kümmert. Die Events Seite wird in absehbarer Zukunft automatisch aus unserem CalDAV Server generiert. Dann wird es auch eine entsprechende Dokumentation geben wie der Prozess dazu exakt aussieht.
